# Generated by Django 4.2.16 on 2024-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('Full', 'FULL'), ('Free', 'Free')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
